package com.myspace.karyawan01;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class datakaryawan implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public datakaryawan() {
    }




}